pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Jeetworld/testng2025/tree/develop.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Reports') {
            steps {
                sh 'mvn surefire-report:report'
                publishHTML([
                  reportDir: 'target/surefire-reports',
                  reportFiles: 'index.html',
                  reportName: 'Test Report'
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.log', allowEmptyArchive: true
        }
        failure {
            mail to: 'team@example.com', subject: 'Test Job Failed', body: 'Check Jenkins.'
        }
    }
}
